Fix typo in witness-get-tree-size-test

diff --git a/tests/witness-get-tree-size-test b/tests/witness-get-tree-size-test
--- a/tests/witness-get-tree-size-test
+++ b/tests/witness-get-tree-size-test
@@ -38,6 +38,6 @@ curl -s -w '%{http_code}\n' http://localhost:7777/get-tree-size/x > test.rsp
 curl -s -w '%{http_code}\n' http://localhost:7777/get-tree-size/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa > test.rsp
 
 [ "404" = "$(tail -1 test.rsp)" ] || (
-    echo 1>&2 'Unexpected status code, expected 404 (Forbidden)'
+    echo 1>&2 'Unexpected status code, expected 404 (Not found)'
     exit 1
 )
